# https://taskfile.dev

version: "3"

silent: true

vars:
  COMPOSE_FILE: docker-compose.yml
  ENV_FILE: docker/.env

tasks:
  default:
    cmd: task -a

  stack:build:
    desc: Build the Prez API and Prez UI images
    cmd: docker compose --env-file {{.ENV_FILE}} -f {{.COMPOSE_FILE}} build

  stack:up:
    desc: Start the Prez API and Prez UI stack
    cmd: docker compose --env-file {{.ENV_FILE}} -f {{.COMPOSE_FILE}} up -d

  stack:down:
    desc: Stop the stack
    cmd: docker compose --env-file {{.ENV_FILE}} -f {{.COMPOSE_FILE}} down

  stack:restart:
    desc: Recreate the stack from the current images and configuration
    cmd: docker compose --env-file {{.ENV_FILE}} -f {{.COMPOSE_FILE}} up -d --force-recreate

  stack:logs:
    desc: Follow logs from the stack
    cmd: docker compose --env-file {{.ENV_FILE}} -f {{.COMPOSE_FILE}} logs -f

  stack:clean:
    desc: Stop the stack and remove its volumes
    cmd: docker compose --env-file {{.ENV_FILE}} -f {{.COMPOSE_FILE}} down -v
